### ISSUE TITLE
Open Sourced agentic chunking

### ISSUE THREAD

**Issue by jnash10** [FullStackRetrieval-com/RetrievalTutorials#2]
Hi Greg,

Thanks for putting out these amazing tutorials.

I'm currently working with a document that's not playing nicely with the PDF parses and want to do Agentic chunking. Unfortunately I don't have access to OpenAI credits and am running stuff locally. 

I'm totally interested in working together to add functionality to be able to do agentic chunking with llamacpp. Currently the extraction_chain gives errors when I do that.

Could you guide me a bit?

**Comment by gkamradt** [comment]
Nice! So first off I love it! Thank you for the energy.

Second off, the agentic chunking package isn't really a package yet. It's just a file on this repo. So if we were to make it official first step would be to 

1) Harden it up a bit, add more tests, error catching, robustness, etc.
2) Add the ability to BYOM Bring-Your-Own-Model via LangChain
3) Get it ready for PyPi and load it up

It is not a top priority for me right now (tons of other things going on) but I'm happy to advise and guide along the way if you wanted to kick it off.

**Comment by jnash10** [comment]
Thanks for taking the time to respond!

Yeah, I'd love to properly test and package both:

- Semantic splitter
- Agentic chunking

For Langchain, I can work on it over the next couple of months as part of my BS Thesis.

If the results are promising, maybe we can even do a paper if you're interested.

**Comment by gkamradt** [comment]
Cool sounds great - I'm hesitant to put both into a package. LangChain and Llama Index already have implementations of the semantic splitter in theirs. It was more of a exploration to begin with.

But if you wanted to start the repo I would help advise

**Comment by jnash10** [comment]
Cool, the SemanticChunker Langchain implementation (inspired by your article): 
https://github.com/langchain-ai/langchain/blame/546b75730358f93e43ac120acf6330b3fe7f742f/libs/experimental/langchain_experimental/text_splitter.py#L68-L128

Could use some work:

- Modular thresholding
- Choice of embedding model, instead of default OpenAI embeddings.
- Recursive splitting for chunks that are too large (with maybe an increased threshold)

I'll push these soon.

I'd love your advice on making an agentic chunker, preferrably within the Langchain Ecosystem or something which can be natively imported into it.

**Comment by gkamradt** [comment]
Cool! I think that LangChain would be open to both of those. They would need to be on the `experimental` side to start.

And yep happy to give advice on the agentic chunker, let me know what you need.

**Comment by JB-Rockstar** [comment]
Hi!

First of all thank you @gkamradt for tutorials! 

I am trying to insert an open source model to the "agentic_chunker.py" file by using Ollama and LiteLLM. 
Instead of this line:

`self.llm = ChatOpenAI(model='gpt-4-1106-preview', openai_api_key=openai_api_key, temperature=0)`

I have added these 2 lines:

`from langchain_openai import OpenAI`
`self.llm = OpenAI(model="mistral", base_url="http://0.0.0.0:4000", api_key="NULL", temperature=0)`

Because OpenAI has more parameters than the opensource models [https://litellm.vercel.app/docs/completion/input](url) , I started the LiteLLM server with this line:

`$ litellm --model ollama/mistral --drop_params`

But, still I get this error: "InternalServerError: Error code: 500 - {'error': {'message': "'eval_count'", 'type': None, 'param': None, 'code': 500}}"
I think it is still because of the missing parameters...

Do you have any ideas?

Thank you.

**Comment by gkamradt** [comment]
Looks like you wouldn't want to use the openai model right?

But rather tha ollama one?
https://python.langchain.com/docs/integrations/llms/ollama
